services:
  - type: web
    name: slack-ubereats-bot
    runtime: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
